spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: costumersdb
      username: usuariomongo
      password: user123
      authentication-database: admin
server:
  port: 8091